spring.application.name=Booking-service
server.port=8082
spring.cloud.stream.bindings.customerEventConsumer-in-0.destination=${TOPIC_CUSTOMER}
spring.cloud.function.definition=customerEventConsumer
spring.docker.compose.file=classpath:compose.yaml
spring.docker.compose.lifecycle-management=start_only
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=booking-service
