spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - TokenRelay=
          routes:
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/v1/customers/**
              filters:
                - TokenRelay=
            - id: booking-service
              uri: lb://booking-service
              predicates:
                - Path=/api/v1/bookings/**
              filters:
                - TokenRelay=

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway-client
            client-secret: XsZfzopSDGdBop0b110IDIUpLTRtvMSC
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER:http://keycloak:8080/realms/gateway}

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
