apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: platform
spec:
  selector:
    app: customer
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: myrepo/customer-service:dev
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://mariadb-customer:3306/customer_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "customer_user"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: mariadb_customer_password
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery.platform.svc.cluster.local:8761/eureka/"
            - name: KEYCLOAK_ISSUER
              value: "https://auth.local/realms/gateway"
